# Model Arguments

model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
processor_name_or_path: Qwen/Qwen2-VL-7B-Instruct

# Data Processing Arguments

train_dataset_path: /home/rahulthapa/repos/OpenBiomedVid/src/openbiomedvid/train/data/openbiomedvid_processed_qwen2_vl_7b_train_dataset

max_seq_length: 16384
packing_algorithm: fast_best_fit_decreasing
assistant_bos: "<|im_start|>assistant\n"
assistant_eos: "<|im_end|>"

# Evaluation Arguments
do_eval: false
eval_strategy: "no"
eval_steps: 10000
# eval_steps: 100

# Training Arguments
# torch_compile_mode: max-autotune
seed: 42
data_seed: 42
bf16: true
tf32: true
torch_dtype: bfloat16
learning_rate: 1.0e-05
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 1
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
warmup_ratio: 0.1
average_tokens_across_devices: true

# Model Saving Arguments
output_dir: /home/rahulthapa/repos/OpenBiomedVid/src/openbiomedvid/train/output/qwen2_vl_7b_train_dataset

overwrite_output_dir: true
save_strategy: "steps"
save_steps: 100
save_total_limit: 10
remove_unused_columns: false
push_to_hub: false


# Logging Arguments
log_level: info
logging_steps: 1  
logging_strategy: steps
report_to:
- wandb

wandb_project: biomedical-finetune