datasets:
  - path: /home/rahulthapa/repos/OpenBiomedVid/src/openbiomedvid/train/data/openbiomedvid_processed
    subset: null
    split: train
    ratio: 1.0

processor_name_or_path: Qwen/Qwen2-VL-7B-Instruct
tokenizer: Qwen/Qwen2-VL-7B-Instruct

num_proc: 64
video_token: <|video|>

output_path: /home/rahulthapa/repos/OpenBiomedVid/src/openbiomedvid/train/data/openbiomedvid_processed_qwen2_vl_7b_train_dataset